// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/protocolpool/v1/budget.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Budget struct {
	RecipientAddress  string      `protobuf:"bytes,1,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	TotalBudget       *types.Coin `protobuf:"bytes,2,opt,name=total_budget,json=totalBudget,proto3" json:"total_budget,omitempty"`
	StartTime         int64       `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	RemainingTranches int64       `protobuf:"varint,4,opt,name=remaining_tranches,json=remainingTranches,proto3" json:"remaining_tranches,omitempty"`
	Period            int64       `protobuf:"varint,5,opt,name=period,proto3" json:"period,omitempty"`
}

func (m *Budget) Reset()         { *m = Budget{} }
func (m *Budget) String() string { return proto.CompactTextString(m) }
func (*Budget) ProtoMessage()    {}
func (*Budget) Descriptor() ([]byte, []int) {
	return fileDescriptor_2414eab590ecb8a3, []int{0}
}
func (m *Budget) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Budget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Budget.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Budget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Budget.Merge(m, src)
}
func (m *Budget) XXX_Size() int {
	return m.Size()
}
func (m *Budget) XXX_DiscardUnknown() {
	xxx_messageInfo_Budget.DiscardUnknown(m)
}

var xxx_messageInfo_Budget proto.InternalMessageInfo

func (m *Budget) GetRecipientAddress() string {
	if m != nil {
		return m.RecipientAddress
	}
	return ""
}

func (m *Budget) GetTotalBudget() *types.Coin {
	if m != nil {
		return m.TotalBudget
	}
	return nil
}

func (m *Budget) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Budget) GetRemainingTranches() int64 {
	if m != nil {
		return m.RemainingTranches
	}
	return 0
}

func (m *Budget) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func init() {
	proto.RegisterType((*Budget)(nil), "cosmos.protocolpool.v1.Budget")
}

func init() {
	proto.RegisterFile("cosmos/protocolpool/v1/budget.proto", fileDescriptor_2414eab590ecb8a3)
}

var fileDescriptor_2414eab590ecb8a3 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x4e, 0x02, 0x31,
	0x14, 0x86, 0xa9, 0x28, 0x09, 0xc5, 0x85, 0x4c, 0x0c, 0x19, 0x48, 0x6c, 0x50, 0x37, 0x6c, 0x68,
	0x33, 0xba, 0xd4, 0x8d, 0x18, 0x2f, 0x80, 0xac, 0xdc, 0x4c, 0x3a, 0x33, 0x0d, 0x36, 0x32, 0x7d,
	0x93, 0xf6, 0x49, 0xf4, 0x16, 0x1e, 0xc6, 0x43, 0xb8, 0x24, 0xae, 0x5c, 0x1a, 0x38, 0x82, 0x17,
	0x30, 0x76, 0x1a, 0x82, 0xcb, 0xf7, 0xff, 0xdf, 0x3f, 0xf3, 0x25, 0xa5, 0xe7, 0x39, 0xb8, 0x12,
	0x9c, 0xa8, 0x2c, 0x20, 0xe4, 0xb0, 0xa8, 0x00, 0x16, 0x62, 0x99, 0x88, 0xec, 0xb9, 0x98, 0x2b,
	0xe4, 0x3e, 0x8e, 0x7a, 0x35, 0xc4, 0x77, 0x21, 0xbe, 0x4c, 0x06, 0x2c, 0x8c, 0x33, 0xe9, 0x94,
	0x58, 0x26, 0x99, 0x42, 0x99, 0x88, 0x1c, 0xb4, 0xa9, 0xc9, 0x41, 0xbf, 0xee, 0x53, 0x7f, 0x89,
	0xdd, 0x8f, 0x9c, 0xfd, 0x10, 0xda, 0x9a, 0xf8, 0x7f, 0x44, 0x77, 0xb4, 0x6b, 0x55, 0xae, 0x2b,
	0xad, 0x0c, 0xa6, 0xb2, 0x28, 0xac, 0x72, 0x2e, 0x26, 0x43, 0x32, 0x6a, 0x4f, 0xe2, 0xcf, 0xf7,
	0xf1, 0x71, 0xd8, 0xdd, 0xd4, 0xcd, 0x3d, 0x5a, 0x6d, 0xe6, 0xd3, 0xa3, 0xed, 0x24, 0xe4, 0xd1,
	0x35, 0x3d, 0x44, 0x40, 0xb9, 0x48, 0x6b, 0xf5, 0x78, 0x6f, 0x48, 0x46, 0x9d, 0x8b, 0x3e, 0x0f,
	0xf3, 0x3f, 0x47, 0x1e, 0x1c, 0xf9, 0x2d, 0x68, 0x33, 0xed, 0x78, 0x3c, 0x48, 0x9c, 0x50, 0xea,
	0x50, 0x5a, 0x4c, 0x51, 0x97, 0x2a, 0x6e, 0x0e, 0xc9, 0xa8, 0x39, 0x6d, 0xfb, 0x64, 0xa6, 0x4b,
	0x15, 0x8d, 0x69, 0x64, 0x55, 0x29, 0xb5, 0xd1, 0x66, 0x9e, 0xa2, 0x95, 0x26, 0x7f, 0x54, 0x2e,
	0xde, 0xf7, 0x58, 0x77, 0xdb, 0xcc, 0x42, 0x11, 0xf5, 0x68, 0xab, 0x52, 0x56, 0x43, 0x11, 0x1f,
	0x78, 0x24, 0x5c, 0x93, 0xab, 0x8f, 0x35, 0x23, 0xab, 0x35, 0x23, 0xdf, 0x6b, 0x46, 0xde, 0x36,
	0xac, 0xb1, 0xda, 0xb0, 0xc6, 0xd7, 0x86, 0x35, 0x1e, 0x4e, 0x6b, 0x4d, 0x57, 0x3c, 0x71, 0x0d,
	0xe2, 0xe5, 0xff, 0x7b, 0xe0, 0x6b, 0xa5, 0x5c, 0xd6, 0xf2, 0xd9, 0xe5, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc1, 0xde, 0xf9, 0x07, 0xb3, 0x01, 0x00, 0x00,
}

func (m *Budget) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Budget) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Budget) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Period != 0 {
		i = encodeVarintBudget(dAtA, i, uint64(m.Period))
		i--
		dAtA[i] = 0x28
	}
	if m.RemainingTranches != 0 {
		i = encodeVarintBudget(dAtA, i, uint64(m.RemainingTranches))
		i--
		dAtA[i] = 0x20
	}
	if m.StartTime != 0 {
		i = encodeVarintBudget(dAtA, i, uint64(m.StartTime))
		i--
		dAtA[i] = 0x18
	}
	if m.TotalBudget != nil {
		{
			size, err := m.TotalBudget.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBudget(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RecipientAddress) > 0 {
		i -= len(m.RecipientAddress)
		copy(dAtA[i:], m.RecipientAddress)
		i = encodeVarintBudget(dAtA, i, uint64(len(m.RecipientAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBudget(dAtA []byte, offset int, v uint64) int {
	offset -= sovBudget(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Budget) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RecipientAddress)
	if l > 0 {
		n += 1 + l + sovBudget(uint64(l))
	}
	if m.TotalBudget != nil {
		l = m.TotalBudget.Size()
		n += 1 + l + sovBudget(uint64(l))
	}
	if m.StartTime != 0 {
		n += 1 + sovBudget(uint64(m.StartTime))
	}
	if m.RemainingTranches != 0 {
		n += 1 + sovBudget(uint64(m.RemainingTranches))
	}
	if m.Period != 0 {
		n += 1 + sovBudget(uint64(m.Period))
	}
	return n
}

func sovBudget(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBudget(x uint64) (n int) {
	return sovBudget(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Budget) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBudget
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Budget: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Budget: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBudget
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBudget
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecipientAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBudget", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBudget
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBudget
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TotalBudget == nil {
				m.TotalBudget = &types.Coin{}
			}
			if err := m.TotalBudget.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingTranches", wireType)
			}
			m.RemainingTranches = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainingTranches |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			m.Period = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Period |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBudget(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBudget
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBudget(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBudget
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBudget
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBudget
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBudget
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBudget        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBudget          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBudget = fmt.Errorf("proto: unexpected end of group")
)
